http:
  host: 'localhost'
  port: 8080

jwt:
  secret: 'secret'
  algorithm: 'HS256'
  signOptions:
    expiresIn: '60s'

db:
  postgres:
    url: 'localhost'
    port: 5432
    database: 'yaml-db'

  sqlite:
    database: 'sqlite.db'

  mariadb:
    url: 'localhost'
    port: 3306
    username: 'root'
    password: '1q2w3e4r'
    database: 'portfolio'