http:
  host: 'localhost'
  port: 8080

jwt:
  secret: 'secret'
  algorithm: 'HS256'
  accessSignOptions:
    expiresIn: '1d'
  refreshSignOptions:
    expiresIn: '7d'

crtypto:
  ENCRYPTION_KEY: 'your-encryption-key'
  IV_LENGTH: 16
  ENCRYPTION_ALGORITHM: 'aes-256-cbc'

db:
  postgres:
    url: 'localhost'
    port: 5432
    database: 'yaml-db'

  sqlite:
    database: 'sqlite.db'
    
  mariadb:
    url: 'localhost'
    port: 3306
    username: 'root'
    password: '1q2w3e4r'
    database: 'portfolio'